version: "3.9"

services:
  app:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile to use
    ports:
      - "8081:8080" # Map port 8081 on the host to port 8080 in the container
    container_name: app
    volumes:
      - .:/app
